<?php
/**
 * Metabox : "Marker Infos"
 * Post types : markers
 * Goal : All the marker infos
 *
 * @package GeoProjects
 */


// Register Metabox

function gp_mbox_marker_infos() {
  	add_meta_box( 'mbox_marker_infos', __( 'Marker Informations', 'geoformat' ), 'gp_mbox_marker_infos_content', 'markers', 'normal', 'core' );
 }

add_action( 'add_meta_boxes', 'gp_mbox_marker_infos' );


//Content of the Metabox
// @param object $post Post Object

function gp_mbox_marker_infos_content( $post ) {
	$gp_options = get_option( 'gp_options' );
	// Get fields values
	$marker_map = get_post_meta( $post->ID, 'gp_map', true );;
    $marker_icon_type = get_post_meta( $post->ID, 'gp_icon_type', true );
    $marker_icon_filename = get_post_meta( $post->ID, 'gp_icon_filename', true );
    $marker_popup_content_order = get_post_meta( $post->ID, 'gp_popup_content_order', true );
    $marker_popup_text = get_post_meta( $post->ID, 'gp_popup_text', true );
    $marker_popup_image = get_post_meta( $post->ID, 'gp_popup_image', true );
    $marker_popup_video = get_post_meta( $post->ID, 'gp_popup_video', true );
    $marker_popup_audio = get_post_meta( $post->ID, 'gp_popup_audio', true );
    $marker_read_more_link = get_post_meta( $post->ID, 'gp_read_more_link', true );
    $marker_lat = get_post_meta( $post->ID, 'gp_lat', true );
    $marker_lng = get_post_meta( $post->ID, 'gp_lng', true );
	$gp_tiles_provider = get_post_meta( $post->ID, 'gp_tiles_provider', true );
	
		if (  empty ($gp_tiles_provider) ) :
            $gp_tiles_provider = $gp_options['map_tiles_provider'];
        else :
			$gp_tiles_provider = get_post_meta( $post->ID, 'gp_tiles_provider', true );
		endif;

    if ( $marker_lat == '' ) { $marker_lat = GP_DEFAULT_MAP_CENTER_LAT; }
    if ( $marker_lng == '' ) { $marker_lng = GP_DEFAULT_MAP_CENTER_LNG; }

	// Nonce Field
    wp_nonce_field( plugin_basename( __FILE__ ), 'mbox_marker_infos_nonce' );

    // Get maps list
    $all_maps = gp_query_get_maps();

    // Set map (if given via url GET and in new marker form)
    if ( $marker_map == '' && isset( $_GET['map'] ) ) {
        if ( gp_query_exists_map( $_GET['map'] ) ) {
            $marker_map = $_GET['map'];
        }
    }

    // Display Mbox content
    ?>

    <h3 style="margin:1em 0"><?php _e( 'Map', 'geoformat' ); ?></h3>

		<?php if ( count( $all_maps ) > 0 ) : ?>
                        
             <p style="margin-bottom:6px">
    			<select name="gp-map" id="gp-map">
    				<option value="0" <?php if ( $marker_map == 0 ) { echo 'selected="selected"'; } ?>>-----</option>
    				<?php foreach ( $all_maps as $map ) : ?>
    					<option value="<?php echo $map->ID; ?>" <?php if ( $marker_map == $map->ID ) { echo 'selected="selected"'; } ?>><?php echo $map->post_title; ?></option>
    				<?php endforeach; ?>
    			</select>
            </p>
                <?php if ( $marker_map != 0 ) : ?>
                    <p style="margin-top:6px">
                         <a href="<?php echo admin_url( 'post.php?post=' . $marker_map . '&action=edit' ); ?>"><?php _e( 'Edit the map', 'geoformat' ); ?></a> - 
                         <a href="<?php echo get_permalink( $marker_map ); ?>"><?php _e( 'See the map', 'geoformat' ); ?></a>
                    </p>
               <?php endif; 
		else : ?>
			<p class="mbox-field-info">
                <?php printf( __( 'No map found. If you want to add this marker to a map, <a href="%1$s">you must create one first</a> (don\'t forget to save this content before clicking on this link).', 'geoformat' ), get_admin_url() . 'post-new.php?post_type=maps' ); ?>
            </p>
		<?php endif; ?>

        <hr class="mb-2" />
			
		<h3 style="margin: 0 0 -20px 0;"><?php _e( 'Icon', 'geoformat' ); ?></h3>
          
            <?php
            // No icon => set to default one
            if ( $marker_icon_type == '' ) {
                $marker_icon_type = 'default';
                $marker_icon_filename = GP_DEFAULT_MARKER_FILE;
            }
            ?>
		<div class="mbox-field-value">
			
			<h4><?php _e('Load your custom marker','geoformat'); ?></h4>
			<input id="meta-image-button" class="button button-primary upload_image_button minibtn" type="button" value="<?php _e('Load image','geoformat');?>" />
				
			<p>
				<em><?php _e('Maximum recommended size: 60 pixels high. To prevent multiple image size generated by WordPress, please go to "Settings/Media" and then set the different image size to 0','geoformat');?></em>
			</p>
				
            <h4><?php _e('Marker preview','geoformat'); ?></h4>
			
			<input type="hidden" name="gp-icon-type" value="<?php echo $marker_icon_type; ?>">
            <input type="hidden" name="gp-icon-filename" value="<?php echo $marker_icon_filename; ?>">

                <div class="mbox-marker-icon-preview">
                    <?php
                    $marker_icon_base_url = ( $marker_icon_type == 'default' ) ? GP_URL_DEFAULT_MARKERS_ICONS : GP_URL_CUSTOM_MARKERS_ICONS;
                    $marker_icon_url = $marker_icon_base_url . '/' . $marker_icon_filename;
                    ?>
                    <img src="<?php echo $marker_icon_url; ?>">
                    <a href="" class="mbox-marker-icon-change"> > <?php _e( 'change', 'geoformat' ); ?></a>
                </div>
				
				<div class="clear clearfix"></div>
				
                <div class="mbox-marker-icons-lists-wrap">
					<ul class="mbox-marker-icons-lists-choice">
						<li>
							<input type="radio" name="gp-marker-icons-list" id="mbox-marker-icons-list-default" value="default" checked="checked">
							<label for="mbox-marker-icons-list-default"><?php _e( 'Default icons', 'geoformat' ); ?></label>
						</li>
						<li>
							<input type="radio" name="gp-marker-icons-list" id="mbox-marker-icons-list-custom" value="custom">
							<label for="mbox-marker-icons-list-custom"><?php _e( 'Custom icons', 'geoformat' ); ?></label>
						</li>
					</ul>
					
					<div class="clear clearfix"></div>

                        <div class="mbox-marker-icons-list-default mbox-marker-icons-list">
                            <?php gp_get_markers_icons_list( 'default' ); ?>
                        </div>
						
                        <div class="mbox-marker-icons-list-custom mbox-marker-icons-list">
                            <img src="<?php echo GP_URL_IMAGE_LOADING; ?>" class="loading" alt="<?php _e( 'Loading', 'geoformat' ); ?>">
						</div>
                    </div>

                    <hr/>
		</div>


    <?php /* Marker Content */ ?>

    <h3><?php _e( 'In the Popup', 'geoformat' ); ?></h3>

    <p class="mbox-info">
        <?php printf( __( '%1$s Note %2$s you can drag an drop created contents for changing display order in the popup. Contents are displayed one above the others in the popup, starting with the created content at left.', 'geoformat' ), '<strong>', ': </strong>' ); ?>
    </p>

    <div class="mbox-marker-content-wrap">
        
        <input type="hidden" name="gp-popup-content-order" value="<?php echo $marker_popup_content_order; ?>">

        <div class="mbox-marker-content-list-wrap clearfix">

            <ul class="mbox-marker-content-list content-types-sortable">

                <?php
                $marker_popup_content_types = array(
                    'text'      => __( 'Text', 'geoformat' ),
                    'image'     => __( 'Image', 'geoformat' ),
                    'video'     => __( 'Video', 'geoformat' ),
                    'audio'     => __( 'Audio', 'geoformat' )
                );
                ?>

                <?php
                $marker_popup_content_order_array = explode( ',', $marker_popup_content_order );
                $first_content_type = ( $marker_popup_content_order != '' ) ? $marker_popup_content_order_array[0] : '';

                // Display created content first
                $cpt = 1;
                if ( $marker_popup_content_order != '' ) :
                    foreach ( $marker_popup_content_order_array as $marker_popup_content_type ) : ?>

                        <li class="mbox-marker-content-<?php echo $marker_popup_content_type; echo ( $cpt == 1 ) ? ' active' : ''; ?>">
                            <a href="" data-content-to-delete="<?php echo $marker_popup_content_type; ?>" class="mbox-marker-content-delete">
                                <span><?php _e( 'Delete', 'geoformat' ); ?></span>
                            </a>
                            <a href="" data-content-to-edit="<?php echo $marker_popup_content_type; ?>" class="mbox-marker-content-edit">
                                <span><?php echo $marker_popup_content_types[$marker_popup_content_type]; ?></span>
                            </a>
                        </li>

                    <?php $cpt++; endforeach;  ?>
                <?php endif; ?>

                <?php
                // Display (but hide) other contents
                foreach ( $marker_popup_content_types as $marker_popup_content_type => $marker_popup_content_type_text ) : ?>

                    <?php if ( !in_array( $marker_popup_content_type, $marker_popup_content_order_array ) ) : ?>

                        <li class="mbox-marker-content-<?php echo $marker_popup_content_type; ?>" style="display:none">
                            <a href="" data-content-to-delete="<?php echo $marker_popup_content_type; ?>" class="mbox-marker-content-delete">
                                <span><?php _e( 'Delete', 'geoformat' ); ?></span>
                            </a>
                            <a href="" data-content-to-edit="<?php echo $marker_popup_content_type; ?>" class="mbox-marker-content-edit">
                                <span><?php echo $marker_popup_content_type_text; ?></span>
                            </a>
                        </li>

                    <?php endif; ?>

                <?php endforeach;  ?>

            </ul>

            <ul class="mbox-marker-content-add-choice clearfix">

                <li class="mbox-marker-content-choice-text" <?php if ( in_array( 'text', $marker_popup_content_order_array ) ) { echo 'style="display:none"'; } ?>>
                    <a href="" data-content-to-add="text" title="<?php _e( 'Add a Text', 'geoformat' ); ?>">
                        <span><?php _e( 'Add a <strong>Text</strong>', 'geoformat' ); ?></span>
                    </a>
                </li>

                <li class="mbox-marker-content-choice-image" <?php if ( in_array( 'image', $marker_popup_content_order_array ) ) { echo 'style="display:none"'; } ?>>
                    <a href="" data-content-to-add="image" title="<?php _e( 'Add an Image', 'geoformat' ); ?>">
                        <span><?php _e( 'Add an <strong>Image</strong>', 'geoformat' ); ?></span>
                    </a>
                </li>

                <li class="mbox-marker-content-choice-video" <?php if ( in_array( 'video', $marker_popup_content_order_array ) ) { echo 'style="display:none"'; } ?>>
                    <a href="" data-content-to-add="video" title="<?php _e( 'Add a Video', 'geoformat' ); ?>">
                        <span><?php _e( 'Add a <strong>Video</strong>', 'geoformat' ); ?></span>
                    </a>
                </li>

                <li class="mbox-marker-content-choice-audio" <?php if ( in_array( 'audio', $marker_popup_content_order_array ) ) { echo 'style="display:none"'; } ?>>
                    <a href="" data-content-to-add="audio" title="<?php _e( 'Add an Audio', 'geoformat' ); ?>">
                        <span><?php _e( 'Add an <strong>Audio</strong>', 'geoformat' ); ?></span>
                    </a>
                </li>

            </ul>

        </div>
        
        <div class="mbox-marker-content-edit-text-wrap mbox-marker-content-edit-pan" <?php echo ( $first_content_type == 'text' ) ? '' : 'style="display:none"'; ?>>

            <?php
            // Display a minimal Wysiwyg editor
            wp_editor(
                $marker_popup_text,
                'gp-popup-text',
                array(
                    'media_buttons' => false,
                    'teeny'         => true,
                    'textarea_rows' => 10,
                    'quicktags'     => false
                )
            );
            ?>

        </div>

        <div class="mbox-marker-content-edit-image-wrap mbox-marker-content-edit-pan" <?php echo ( $first_content_type == 'image' ) ? '' : 'style="display:none"'; ?>>

            <?php
            // Get Image HTML
            if ( $marker_popup_image != '' ) {
                $marker_popup_image_html = wp_get_attachment_image( $marker_popup_image, 'medium' );

                // If image does not exist anymore, reset field
                if ( $marker_popup_image_html == '' ) {
                    $marker_popup_image = '';
                }
            }
            ?>

            <input type="hidden" name="gp-popup-image" value="<?php echo $marker_popup_image; ?>">
            
            <div class="mbox-marker-content-edit-image-preview">
                <?php if ( $marker_popup_image != '' ) { echo $marker_popup_image_html; } ?>
            </div>

            <p class="mbox-marker-content-edit-buttons">
                <a href="" class="mbox-marker-content-edit-image-choose" <?php if ( $marker_popup_image != '' ) { echo 'style="display:none"'; } ?>>
                    <?php _e( 'Choose an Image', 'geoformat' ); ?>
                </a>
                <a href="" class="mbox-marker-content-edit-image-delete" <?php if ( $marker_popup_image == '' ) { echo 'style="display:none"'; } ?>>
                    <?php _e( 'Remove image', 'geoformat' ); ?>
                </a>
            </p>

        </div>

        <div class="mbox-marker-content-edit-video-wrap mbox-marker-content-edit-pan" <?php echo ( $first_content_type == 'video' ) ? '' : 'style="display:none"'; ?>>
            
            <p>
                <label for="mbox-marker-content-edit-video-url"><?php _e( 'URL of the video', 'geoformat' ); ?></label>
                <input type="text" name="gp-popup-video" id="mbox-marker-content-edit-video-url" value="<?php echo $marker_popup_video; ?>">
            </p>

            <div class="mbox-marker-content-edit-video-preview" <?php if ( $marker_popup_video == '' ) { echo 'style="display:none"'; } ?>>
                <?php
                if ( $marker_popup_video != '' ) {
                    echo wp_oembed_get( $marker_popup_video );
                }
                ?>
            </div>

            <p class="mbox-marker-content-edit-buttons">
                <a href="" class="mbox-marker-content-edit-video-delete" <?php if ( $marker_popup_video == '' ) { echo 'style="display:none"'; } ?>>
                    <?php _e( 'Remove video', 'geoformat' ); ?>
                </a>
            </p>

        </div>

        <div class="mbox-marker-content-edit-audio-wrap mbox-marker-content-edit-pan" <?php echo ( $first_content_type == 'audio' ) ? '' : 'style="display:none"'; ?>>

            <?php
            // Get Audio filename
            if ( $marker_popup_audio != '' ) {

                $audioAttachment = gp_query_get_attachment( $marker_popup_audio );

                // If audio does not exist anymore, reset field
                if ( $audioAttachment == '' ) {
                    $marker_popup_audio = '';
                }

            }
            ?>

            <input type="hidden" name="gp-popup-audio" value="<?php echo $marker_popup_audio; ?>">
            
            <div class="mbox-marker-content-edit-audio-preview">
                <?php
                if ( $marker_popup_audio != '' ) {
                    echo do_shortcode( '[audio mp3="' . $marker_popup_audio . '"][/audio]' );
                }
                ?>
            </div>

            <p class="mbox-marker-content-edit-buttons">
                <a href="" class="mbox-marker-content-edit-audio-choose" <?php if ( $marker_popup_audio != '' ) { echo 'style="display:none"'; } ?>>
                    <?php _e( 'Choose a MP3 file', 'geoformat' ); ?>
                </a>
                <a href="" class="mbox-marker-content-edit-audio-delete" <?php if ( $marker_popup_audio == '' ) { echo 'style="display:none"'; } ?>>
                    <?php _e( 'Remove audio file', 'geoformat' ); ?>
                </a>
            </p>

        </div>
         <hr class="mt-2"/>
    </div>



    <?php /* Read More Link  */ ?>

     <h3><?php _e( 'Read more link', 'geoformat' ); ?> <small>(<?php _e( 'Optional', 'geoformat' ); ?>)</small></h3>

    <div class="mbox-marker-read-more-link-wrap">

         <div class="mbox-marker-content-edit-read-more-link-wrap mbox-marker-read-more-link-edit-pan">
            <div class="mb-1">
                <?php printf( __( 'By default, the Read more link goes to the Marker page. To redirect to a different url, type it here.', 'geoformat' ), '<strong>', ': </strong>' ); ?>
            </div>
            <div class="d-block d-xl-flex">
                <label class="mr-1" for="mbox-marker-content-read-more-link"><?php _e( 'Redirect Read More Link', 'geoformat' ); ?></label>
                <input type="text" class="d-block" name="gp-read-more-link" id="mbox-marker-content-read-more-link" value="<?php echo $marker_read_more_link; ?>">
            </div>
                
        </div>
         <hr class="mt-3"/>
    </div>


    <?php /* Tiles Provider */ ?>
    <div>
        <h3><?php _e( 'Tiles Provider', 'geoformat' ); ?></h3>
        <div class="d-flex pb-2" id="tilesProvider">
            <label class="align-self-center mr-2"><?php _e( 'Choose a tiles provider :', 'geoformat' ); ?></label>
            <select class="align-self-center" name="gp-tiles-provider" id="gp-tiles-provider">
                    <option value="osm" <?php selected($gp_tiles_provider, "osm"); ?>>OpenStreetMap</option>
                    <option value="cyclosm" <?php selected($gp_tiles_provider, "cyclosm"); ?>>CyclOSM</option>
                    <option value="esrigrey" <?php selected($gp_tiles_provider, "esrigrey"); ?>>Esri WorldGrayCanvas</option>
                    <option value="esristreet" <?php selected($gp_tiles_provider, "esristreet"); ?>>Esri WorldStreetMap</option>
                    <option value="esriworld" <?php selected($gp_tiles_provider, "esriworld"); ?>>Esri WorldImagery</option>
                    <option value="opentopo" <?php selected($gp_tiles_provider, "opentopo"); ?>> OpenTopoMap</option>
                    <option value="osmhot" <?php selected($gp_tiles_provider, "osmhot"); ?>>OpenStreetMap.HOT</option>
                    <option value="hydda" <?php selected($gp_tiles_provider, "hydda"); ?>>Hydda Full</option>
                    <option value="worldimagery" <?php selected($gp_tiles_provider, "worldimagery"); ?>>Esri.Shaded.Relief</option>
                    <option value="delorme" <?php selected($gp_tiles_provider, "delorme"); ?>>Esri.DeLorme</option>
                    <option value="stadia_alida" <?php selected($gp_tiles_provider, "stadia_alida"); ?>>Stadia Alida</option>
                    <option value="stadia_outdoors" <?php selected($gp_tiles_provider, "stadia_outdoors"); ?>>Stadia Outdoors</option>
                    <option value="stadia_osmbright" <?php selected($gp_tiles_provider, "stadia_osmbright"); ?>>Stadia OSM Bright</option>
                    <option value="stadia_dark" <?php selected($gp_tiles_provider, "stadia_dark"); ?>>Stadia Dark</option>
                    <option value="mtmap" <?php selected($gp_tiles_provider, "mtmap"); ?>>MT Map</option>
                    <option value="stamentoner" <?php selected($gp_tiles_provider, "stamentoner"); ?>>Stamen Toner</option>
                    <option value="stamentonerlight" <?php selected($gp_tiles_provider, "stamentonerlight"); ?>>Stamen Toner Light</option>
                    <option value="stamenwater" <?php selected($gp_tiles_provider, "stamenwater"); ?>>Stamen Watercolor</option>
                    <option value="stamenterrain" <?php selected($gp_tiles_provider, "stamenterrain"); ?>>Stamen Terrain</option>
                    <option value="geoportail" <?php selected($gp_tiles_provider, "geoportail"); ?>>Geoportail FR</option>
                    <option value="geoportailimg" <?php selected($gp_tiles_provider, "geoportailimg"); ?>>Geoportail IMG</option>
                    <option value="geoportailorthos" <?php selected($gp_tiles_provider, "geoportailorthos"); ?>>Geoportail Orthos</option>
                    <option value="mapbox" <?php selected($gp_tiles_provider, "mapbox"); ?>>MapBox*</option>
             </select>
        </div>
        <div class="help-notice">
        <?php _e('Select the background with which you want to preview. Please, save it to view the change. It will only affect the markers\' preview, not the original map. To do so, you have to edit the original map that you have created.','geoformat'); ?>
        </div>
        <div><small><?php _e( '*To use MapBox, don\'t forget to complete the field "MapBox access token" within the setting page.', 'geoformat' ); ?></small>
         </div>
   
        <p><a href="<?php echo admin_url( 'post.php?post=' . $marker_map . '&action=edit' ); ?>"><?php _e( 'Edit the map', 'geoformat' ); ?></a>  
        </p>
         <hr class="mt-3"/>
    </div>


    <div class="mbox-marker-geo-wrap">

        <?php /* Marker Geolocation */ ?>
    
        <h3><?php _e( 'Geolocation', 'geoformat' ); ?></h3>
        <div>Vous pouvez positionner le marqueur de 4 façons différentes : </div>
       
        <div class="d-flex pt-3">
            <div class="dashicons-before dashicons-admin-site-alt3" aria-hidden="true"></div>
            <big class="pl-1 bold">Par coordonnées</big>
        </div>
        <div class="d-block d-md-flex pl-3">
            <div class="pr-3 pt-1">
                <label for="mbox-marker-lat"><?php _e( 'Latitude', 'geoformat' ); ?></label>
                <input type="text" name="gp-lat" id="mbox-marker-geo-lat" value="<?php echo $marker_lat; ?>">
            </div>
            <div class="pr-3 pt-1">
                <label for="mbox-marker-lng"><?php _e( 'Longitude', 'geoformat' ); ?></label>
                <input type="text" name="gp-lng" id="mbox-marker-geo-lng" value="<?php echo $marker_lng; ?>">
            </div>
           
        </div>
        <div class="pl-3 pt-1"><a href="" class="map-search-lng-lat-button button button-secondary">Positionner le marqueur</a></div>

       
        <div class="d-flex pt-3 locate-me">
            <div class="dashicons-before dashicons-location-alt" aria-hidden="true"></div>
            <big class="pl-1 bold pb-1">Par géolocalisation sur le terrain</big>
        </div>
        <div class="pl-3">
            <a href="" class="locate-me-button button button-secondary">Détecter ma position</a>
        </div>



		<div class="d-flex pt-3">
            <div class="dashicons-before dashicons-email-alt" aria-hidden="true"></div>
            <big class="pl-1 bold">Par adresse postale</big>
        </div>
        <div class="pl-3 pb-1 help-notice"><?php _e( 'You can search for a postal address (powered by <a href="http://nominatim.openstreetmap.org/" target="_blank">OpenStreetMap Nominatim</a>). If you can\'t find an address, try to be more precise or test other keywords.', 'geoformat' ); ?></div>
		<div class="gp-leaflet-map-container">
		
		
		<?php 
			
			$overlaymap = get_post_meta( $marker_map, 'custom_image_displaying', true ); 
			
			if (empty ($overlaymap) ) :
				$overlaymap = '';
			else: 
				$overlaymap = get_post_meta( $marker_map, 'custom_image_displaying', true ); 
			endif;
			
			$custombgmap = get_post_meta( $marker_map, 'custom_image_download', true );

			if (empty ($custombgmap) ) :
				$custombgmap = '';
			else: 
				$custombgmap = get_post_meta( $marker_map, 'custom_image_download', true );
			endif;
			
			$zoom = get_post_meta( get_the_ID(), 'gp_tiles_zoom', true );
			
			if (empty ($zoom) ) :
				$zoom =  GP_DEFAULT_MAP_ZOOM;
			else: 
				$zoom = get_post_meta( get_the_ID(), 'gp_tiles_zoom', true );
			endif;	
			
			$custominzoom = get_post_meta( $marker_map, 'custom_image_minzoom', true ); 
			
			if ( empty ($custominzoom) ) :
				$custominzoom = '';
			else: 
				$custominzoom = get_post_meta( $marker_map, 'custom_image_minzoom', true );
			endif;	
		?>
		
		<input type="hidden" name="gp-overlay-map" value="<?php echo $overlaymap; ?>">
		<input type="hidden" name="gp-custombg-map" value="<?php echo $custombgmap; ?>">
		<input type="hidden" name="gp-custombg-minzoom" value="<?php echo $custominzoom; ?>">



		<div class="d-flex pt-2">
            <div class="dashicons-before dashicons-move" aria-hidden="true"></div>
            <big class="pl-1 bold">Manuellement</big>
        </div>
        <div class="pl-3 help-notice">
            <div><?php _e( 'Drag the marker to the desired position.', 'geoformat' ); ?><?php _e( 'You can zoom and pan to the desired location and bring back the marker there by clicking the button "center marker here".', 'geoformat' ); ?></div>
            
        </div>
        

            <div class="gp-leaflet-map-wrap">
                <div id="mbox-marker-map" class="gp-leaflet-map"
                    <?php if ( $overlaymap !='replace') : ?>data-map-tiles="<?php echo $gp_tiles_provider; ?>"<?php endif; ?>
                    data-map-center-lat="<?php echo $marker_lat; ?>"
                    data-map-center-lng="<?php echo $marker_lng; ?>"
                    <?php if ( $overlaymap !='replace') : ?>data-map-zoom="<?php echo $zoom; ?>" <?php endif; ?>
                    data-map-drag-marker="1"
                    data-map-drag-marker-icon-type="<?php echo $marker_icon_type; ?>"
                    data-map-drag-marker-icon-filename="<?php echo $marker_icon_filename; ?>"
                    data-map-center-here="1"
                    data-map-lat-field="mbox-marker-geo-lat"
                    data-map-lng-field="mbox-marker-geo-lng"
                    data-map-search-box="1"></div>
            </div>
		</div>
	<div class="clear"></div>
    </div>
	<div class="clear"></div>

<?php
}

/**
 * Save the Metaboxes data
 * @param  Int $post_id ID of the post
 */
function gp_save_mbox_marker_infos( $post_id ) {
  
    // Don't do anything for auto-save
    if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) 
        return $post_id;

    // No nonce ?
    if( !isset( $_POST['mbox_marker_infos_nonce'] ) )
        return $post_id;

    // Check nonce
    if ( !wp_verify_nonce( $_POST['mbox_marker_infos_nonce'], plugin_basename( __FILE__ ) ) )
        return;

    // Check permissions
    if ( !current_user_can( 'edit_posts', $post_id ) )
        return;

    // Mbox submitted ?
    if ( isset( $_POST['gp-icon-type'] ) ) {

        // Save map
        update_post_meta( $post_id, 'gp_map',  trim( $_POST['gp-map'] ) );

        // Save icon type
        update_post_meta( $post_id, 'gp_icon_type',  trim( $_POST['gp-icon-type'] ) );

        // Save icon filename
        update_post_meta( $post_id, 'gp_icon_filename',  trim($_POST['gp-icon-filename']) );
        
        // Remove empty contents from the content order
        
		$content_order = explode( ',', trim( $_POST['gp-popup-content-order'] ) );
        
	
			$new_content_order = array();

			foreach ( $content_order as $content_type ) {
				$new_content_order[] = $content_type;
				
			}
			
	
        // Save content order
        update_post_meta( $post_id, 'gp_popup_content_order', implode( ',', $new_content_order ) );

        // Save popup contents
        update_post_meta( $post_id, 'gp_popup_text', ( in_array( 'text', $new_content_order ) ) ? trim(  wp_kses_post($_POST['gp-popup-text'] )) : '' );
        update_post_meta( $post_id, 'gp_popup_image', ( in_array( 'image', $new_content_order ) ) ? trim(  sanitize_text_field($_POST['gp-popup-image'] )) : '' );
        update_post_meta( $post_id, 'gp_popup_video', ( in_array( 'video', $new_content_order ) ) ? trim(  sanitize_text_field($_POST['gp-popup-video'] )) : '' );
        update_post_meta( $post_id, 'gp_popup_audio', ( in_array( 'audio', $new_content_order ) ) ? trim(  sanitize_text_field($_POST['gp-popup-audio'] )) : '' );

        // Save Read More Link
        update_post_meta( $post_id, 'gp_read_more_link',  sanitize_text_field($_POST['gp-read-more-link'] ));

        // Save geolocation
        update_post_meta( $post_id, 'gp_lat', trim( $_POST['gp-lat'] ) );
        update_post_meta( $post_id, 'gp_lng', trim( $_POST['gp-lng'] ) );
		
		//Save map tiles provider
        update_post_meta( $post_id, 'gp_tiles_provider',  sanitize_text_field($_POST['gp-tiles-provider'] ));
		
		//Save hidden metadata from map
		
		update_post_meta( $post_id, 'gp-overlay-map', trim( $_POST['gp-overlay-map'] ) );
		update_post_meta( $post_id, 'gp-custombg-map', trim( $_POST['gp-custombg-map'] ) );
		update_post_meta( $post_id, 'gp-custombg-minzoom', trim( $_POST['gp-custombg-minzoom'] ) );

    }

}

add_action( 'save_post', 'gp_save_mbox_marker_infos' );

//Add a notice
function markers_admin_notice(){
    global $typenow,$pagenow;
    if  (in_array( $pagenow, array( 'post.php', 'post-new.php' ))  && "markers" == $typenow ) { ?>
         <div class="notice notice-warning is-dismissible" style="padding:10px;">
             <?php _e("To preview a map where an image replaces the tiles on a map, give that marker a title, link it to the map, and save your marker. If the marker does not appear on the image, click on the'center the marker' button to display it.", "geoformat"); ?>
         </div>
    <?php }
}
add_action('admin_notices', 'markers_admin_notice');
?>